#!/usr/bin/env bash
#Process and PID file
PID_FILE="/var/run/myscript.pid"
echo $$ > "$PID_FILE"
cleanup() {
    rm -f "$PID_FILE"
    exit
}
trap 'echo "I hate the kill command"; cleanup' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'cleanup' SIGQUIT
while true; do
    echo "To infinity and beyond"
    sleep 2
done
