#!/usr/bin/env bash
# 11-manage_my_process
PID_FILE="/var/run/my_process.pid"
PROCESS_NAME="./manage_my_process"

case "$1" in
    start)
        $PROCESS_NAME &
        echo $! > "$PID_FILE"
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f "$PID_FILE" ]; then
            PID=$(cat "$PID_FILE")
            kill "$PID"
            rm -f "$PID_FILE"
            echo "manage_my_process stopped"
        fi
        ;;
    restart)
        ./11-manage_my_process stop > /dev/null
        ./11-manage_my_process start > /dev/null
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
