#!/usr/bin/env bash
# 11-manage_my_process

PID_FILE="/var/run/my_process.pid"
PROCESS_NAME="./manage_my_process"

case "$1" in
    start)
        $PROCESS_NAME &
        $! > "$PID_FILE"
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f "$PID_FILE" ]; then
            $(cat "$PID_FILE")
            rm -f "$PID_FILE"
            echo "manage_my_process stopped"
        fi
        ;;
    restart)
        $0 stop
        $0 start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
